#ifndef LIVE_ROOM_SENSOR_VERSION_H
#define LIVE_ROOM_SENSOR_VERSION_H

#ifdef USE_NEW_MINEW_RADAR
#define FIRMWARE_STRING FIRMWARE_VERSION "-minew"
#else
#define FIRMWARE_STRING FIRMWARE_VERSION "-micradar"
#endif

#endif //LIVE_ROOM_SENSOR_VERSION_H
